---
title: "Testing systemfonts/ragg on Github Actions"
---

```{r}
getwd()
```

# {.tabset}


## Without `register_font()`

```{r}
Sys.info()
```


```{r setup, include=F}
library(magrittr)
library(ggplot2)
library(ragg)

knitr::opts_chunk$set(echo = T, warning = T, dev = "ragg_png")
```

```{r}
ggplot(mtcars, aes(mpg, wt)) +
  geom_point() +
  theme(text = element_text(family = "IBM Plex Sans"),
        plot.title = element_text(family = "IBM Plex Sans", face = "bold")) +
  labs(title = "This is a title 1000999",
       subtitle = "This is a subtitle 1000999")
```

```{r}
sfnts <- systemfonts::system_fonts()
```

```{r}
"hi"
```

```{r}
sfnts
```

```{r}
systemfonts::register_font("IBM Plex Sans Condensed", 
                           plain = system.file("fonts", "plex",
                                               "IBMPlexSansCondensed-Regular.ttf",
                                               package = "ptrr"))
systemfonts::register_font("IBM Plex Sans", 
                           plain = system.file("fonts", "plex", 
                                              "IBMPlexSans-Regular.ttf",
                                               package = "ptrr"),
                           bold = system.file("fonts", "plex", 
                                              "IBMPlexSans-Bold.ttf",
                                               package = "ptrr"))
```

```{r}
systemfonts::registry_fonts()
```



```{r}
sfnts[grepl("[Pp]lex", sfnts$family),c("family", "style", "italic", "monospace")]
```


```{r}
3*4
```

```{r}
```

```{r}
systemfonts::match_font("IBM Plex Sans")
```

## Plain plot

```{r}
ggplot(mtcars, aes(mpg, wt)) +
  geom_point() +
  theme(text = element_text(family = "IBM Plex Sans"),
        plot.title = element_text(family = "IBM Plex Sans", face = "bold")) +
  labs(title = "This is a title 1000999",
       subtitle = "This is a subtitle 1000999")
```

```{r}
ptrr::set_ptrr_ggplot_fonts("IBM Plex Sans Condensed")
```

## Test set fonts in geoms

```{r}
ggplot(mpg[1:10,], aes(cty, hwy)) +
  geom_point() +
  geom_text(aes(label = trans)) +
  theme(text = element_text(family = "IBM Plex Sans"),
        plot.title = element_text(family = "IBM Plex Sans", face = "bold")) +
  labs(title = "This is a title 1000999",
       subtitle = "This is a subtitle 1000999")
```

## Test theme with fonts

```{r}
ggplot(mpg[1:10,], aes(cty, hwy)) +
  geom_point() +
  geom_text(aes(label = trans)) +
  labs(title = "This is a title 1000999",
       subtitle = "This is a subtitle 1000999") +
  ptrr::theme_ptrr()
```

## Test loading font from user library path

```{r}
systemfonts::register_font("IBM Plex Sans Condensed 2", 
                           plain = '/Users/runner/Library/Fonts/IBMPlexSansCondensed-Regular.otf')
```

```{r}
systemfonts::registry_fonts()
```

```{r}
ggplot(mtcars, aes(mpg, wt)) +
  geom_point() +
  theme(text = element_text(family = "IBM Plex Sans Condensed 2"),
        plot.title = element_text(family = "IBM Plex Sans Condensed 2")) +
  labs(title = "This is a title 1000999",
       subtitle = "This is a subtitle 1000999")
```
